---
  - name: "prepare env"
    hosts: localhost
    connection: local 
    become: yes
    tasks:
    - name: Install i3 user repo
      ansible.builtin.get_url:
        url: https://packages.test.osinfra.cn/coprs/mywaaagh_admin/i3wm/repo/openeuler-{{ansible_distribution_version}}/mywaaagh_admin-i3wm-openeuler-{{ansible_distribution_version}}.repo
        dest: /etc/yum.repos.d/i3wm.repo
        mode: '0644'
      when: ansible_facts['distribution'] == "openEuler"

  - name: "save real name"
    hosts: localhost
    connection: local 
    tasks:
    - name: "save real name"
      ansible.builtin.shell:
        cmd: whoami
      register: real_name

  - name: "Custom a waaagh workspace"
    hosts: localhost
    connection: local 
    become: yes
    tasks:
    - name: Install the latest version of my favorite packages
      ansible.builtin.package:
        state: latest
        name: 
          - git
          - python-pip
          - vim
          - fish

    - name: Set default shell to fish
      ansible.builtin.user:
        name: "{{ real_name.stdout }}"
        shell: /usr/bin/fish

    - name: "save fish version"
      ansible.builtin.shell:
        cmd: fish -v | grep -oE '[0-9.]+'
      register: fish_versioin


    - name: Install my editor
      ansible.builtin.package:
        state: latest
        name: 
          - neovim
      when: ansible_facts['distribution'] != "openEuler"

    - name: Install the latest version of package needed by i3wm
      ansible.builtin.package:
        state: latest
        name: 
          - i3
          - i3lock
          - i3blocks
          - dmenu
          - lightdm

    - name: Install the latest version of more extra packages
      ansible.builtin.package:
        state: latest
        name: 
          - xorg-x11-server
          - xorg-x11-drv-*
          - google-noto-cjk-fonts
      when: ansible_facts['distribution'] == "openEuler"

  - name: "install good look nerd fonts"
    hosts: localhost
    connection: local 
    tasks:
    - name: Install the latest version of fontconfig
      ansible.builtin.package:
        state: latest
        name: 
          - fontconfig

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
        state: directory
        mode: '0755'

    - name: Install Caskaydia mono regular
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Nerd%20Font%20Complete%20Mono%20Regular.otf
        dest: "{{ ansible_env.HOME }}/.local/share/fonts"

    - name: Install Caskaydia regular
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Nerd%20Font%20Complete%20Regular.otf
        dest: "{{ ansible_env.HOME }}/.local/share/fonts"

    - name: install fonts
      ansible.builtin.shell:
        cmd: fc-cache -f -v

  - name: "install fisher and tide"
    hosts: localhost
    connection: local 
    tasks:
    - name: Install the latest version of fish
      ansible.builtin.package:
        state: latest
        name: 
          - fish

    - name: get fisher scripts
      ansible.builtin.get_url:
        url: https://git.io/fisher 
        dest: /tmp/fisher
        mode: '0755'

    - name: install fisher
      ansible.builtin.shell:
        cmd: source /tmp/fisher && fisher install jorgebucaran/fisher
        executable: /bin/fish

    - name: remove fisher scripts
      ansible.builtin.file:
        path: /tmp/fisher
        state: absent

    - name: install tide
      ansible.builtin.shell:
        cmd: fisher install IlanCosman/tide@v5.0.1
        executable: /bin/fish
      when: fish_versioin.stdout is version('3.3.1', '==')

    - name: install tide
      ansible.builtin.shell:
        cmd: fisher install IlanCosman/tide@v5.3.0
        executable: /bin/fish
      when: fish_versioin.stdout is version('3.4.1', '<=') and fish_versioin.stdout is version('3.4.0', '>=')


    - name: install tide
      ansible.builtin.shell:
        cmd: fisher install IlanCosman/tide@v5.4.0
        executable: /bin/fish
      when: fish_versioin.stdout is version('3.5.0', '<=') and fish_versioin.stdout is version('3.5.1', '>=')

    - name: install tide
      ansible.builtin.shell:
        cmd: fisher install IlanCosman/tide@v5
        executable: /bin/fish
      when: fish_versioin.stdout is version('3.5.1', '>')



